max_concurrent_uploads = 3

[creator]
type = "user"
id = 290622415

[codegen]
style = "flat"
strip_extension = true

[inputs.ui]
path = "assets/interface/exports/*.png"
output_path = "tmp/tungsten/UI.luau"
type = "image"
packable = false
bleed = false
